Experiment 20

Aim:Covid Data Analysis Project Analysis

Name:Shravya Srivastava

PRN:25070123106

In [6]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv("/content/covid_19_data.csv")
data.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [9]:
data = data.drop(['SNo','Last Update'],axis=1)
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  306429 non-null  object
 1   Province/State   228326 non-null  object
 2   Country/Region   306429 non-null  object
 3   Confirmed        306429 non-null  float64
 4   Deaths           306429 non-null  float64
 5   Recovered        306429 non-null  float64
dtypes: float64(3), object(3)
memory usage: 14.0+ MB

In [11]:
data['ObservationDate'] = data['ObservationDate'].astype('datetime64[ns]')
data['Confirmed'] = data['Confirmed'].fillna(0).astype('int64')
data['Deaths'] = data['Deaths'].fillna(0).astype('int64')
data['Recovered'] = data['Recovered'].fillna(0).astype('int64')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299657 entries, 0 to 299656
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  299657 non-null  datetime64[ns]
 1   Province/State   222989 non-null  object
 2   Country/Region   299657 non-null  object
 3   Confirmed        299657 non-null  int64
 4   Deaths           299657 non-null  int64
 5   Recovered        299657 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 13.7+ MB

In [ ]:
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      2020-01-22          Anhui  Mainland China          1       0          0
1      2020-01-22        Beijing  Mainland China         14       0          0
2      2020-01-22      Chongqing  Mainland China          6       0          0
3      2020-01-22         Fujian  Mainland China          1       0          0
4      2020-01-22          Gansu  Mainland China          0       0          0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299657 entries, 0 to 299656
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  299657 non-null  datetime64[ns]
 1   Province/State   222989 non-null  object
 2   Country/Region   299657 non-null  object
 3   Confirmed        299657 non-null  int64
 4   Deaths           299657 non-null  int64
 5   Recovered        299657 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 13.7+ MB

In [ ]:
# Active Case
data['Active'] = data['Confirmed'] - data['Recovered'] - data['Deaths']
data.head(50)

data.iloc[50:100]

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
50,2020-01-23,Heilongjiang,Mainland China,2,0,0,2
51,2020-01-23,Henan,Mainland China,5,0,0,5
52,2020-01-23,Hong Kong,Hong Kong,2,0,0,2
53,2020-01-23,Hubei,Mainland China,444,17,28,399
54,2020-01-23,Hunan,Mainland China,9,0,0,9
55,2020-01-23,Inner Mongolia,Mainland China,0,0,0,0
56,2020-01-23,Jiangsu,Mainland China,5,0,0,5
57,2020-01-23,Jiangxi,Mainland China,7,0,0,7
58,2020-01-23,Jilin,Mainland China,1,0,0,1
59,2020-01-23,Liaoning,Mainland China,3,0,0,3
60,2020-01-23,Macau,Macau,2,0,0,2
61,2020-01-23,Ningxia,Mainland China,1,0,0,1
62,2020-01-23,Qinghai,Mainland China,0,0,0,0
63,2020-01-23,Shaanxi,Mainland China,3,0,0,3
64,2020-01-23,Shandong,Mainland China,6,0,0,6
65,2020-01-23,Shanghai,Mainland China,16,0,0,16
66,2020-01-23,Shanxi,Mainland China,1,0,0,1
67,2020-01-23,Sichuan,Mainland China,8,0,0,8
68,2020-01-23,Taiwan,Taiwan,1,0,0,1
69,2020-01-23,Tianjin,Mainland China,4,0,0,4
70,2020-01-23,Tibet,Mainland China,0,0,0,0
71,2020-01-23,Washington,US,1,0,0,1
72,2020-01-23,Xinjiang,Mainland China,2,0,0,2
73,2020-01-23,Yunnan,Mainland China,2,0,0,2
74,2020-01-23,Zhejiang,Mainland China,27,0,0,27
75,2020-01-23,NaN,Japan,1,0,0,1
76,2020-01-23,NaN,Thailand,4,0,2,2
77,2020-01-23,NaN,South Korea,1,0,0,1
78,2020-01-23,NaN,Singapore,1,0,0,1
79,2020-01-23,NaN,Philippines,0,0,0,0
80,2020-01-23,NaN,Malaysia,0,0,0,0
81,2020-01-23,NaN,Vietnam,2,0,0,2
82,2020-01-23,NaN,Australia,0,0,0,0
83,2020-01-23,NaN,Mexico,0,0,0,0
84,2020-01-23,NaN,Brazil,0,0,0,0
85,2020-01-23,NaN,Colombia,0,0,0,0
86,2020-01-23,Unknown,China,0,0,0,0
87,2020-01-23,NaN,Kiribati,0,0,0,0
88,2020-01-24,Hubei,Mainland China,549,24,31,494
89,2020-01-24,Guangdong,Mainland China,53,0,2,51
90,2020-01-24,Zhejiang,Mainland China,43,0,1,42
91,2020-01-24,Beijing,Mainland China,36,0,1,35
92,2020-01-24,Chongqing,Mainland China,27,0,0,27
93,2020-01-24,Hunan,Mainland China,24,0,0,24
94,2020-01-24,Guangxi,Mainland China,23,0,0,23
95,2020-01-24,Shanghai,Mainland China,20,0,1,19
96,2020-01-24,Jiangxi,Mainland China,18,0,0,18
97,2020-01-24,Sichuan,Mainland China,15,0,0,15
98,2020-01-24,Shandong,Mainland China,15,0,0,15
99,2020-01-24,Anhui,Mainland China,15,0,0,15

In [ ]:
# last/current date
data['ObservationDate'].max()

Timestamp('2021-05-21 00:00:00')

In [ ]:
# Fetch latest date data
latest_data = data[data['ObservationDate'] == data['ObservationDate'].max()]
latest_data.head()

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
299544,2021-05-21,NaN,Afghanistan,65080,2782,55790,6508
299545,2021-05-21,NaN,Albania,132153,2441,128425,1287
299546,2021-05-21,NaN,Algeria,126434,3405,88066,34963
299547,2021-05-21,NaN,Andorra,13569,127,13234,208
299548,2021-05-21,NaN,Angola,31909,709,26513,4687

In [ ]:
latest_data.shape

(113, 7)

In [ ]:
latest_data['Country/Region'].value_counts()

Country/Region
Afghanistan    1
Albania        1
Algeria        1
Andorra        1
Angola         1
              ..
Morocco        1
Mozambique     1
Namibia        1
Nepal          1
New Zealand    1
Name: count, Length: 113, dtype: int64

In [ ]:
latest_data['Country/Region'].nunique()

113

In [ ]:
latest_data['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Diamond Princess',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See',
       'Honduras', 'Hungary', 'Iceland', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Ivory Coast', 'Jamaica', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Micronesia',
       'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Namibia', 'Nepal', 'New Zealand'], dtype=object)

In [ ]:
# Count of cases for each country
countries = latest_data.groupby("Country/Region")[["Confirmed","Deaths","Recovered","Active"]].sum()

countries = countries.reset_index()

In [ ]:
countries

    Country/Region  Confirmed  Deaths  Recovered  Active
0      Afghanistan      65080    2782      55790    6508
1          Albania     132153    2441     128425    1287
2          Algeria     126434    3405      88066   34963
3          Andorra      13569     127      13234     208
4           Angola      31909     709      26513    4687
..             ...        ...     ...        ...     ...
108        Morocco     516449    9115     504757    2577
109     Mozambique      70551     831      68845     875
110        Namibia      52433     759      48951    2723
111          Nepal     497052    6024     374836  116192
112    New Zealand          0       0          0       0

[113 rows x 5 columns]

In [ ]:
countries[countries['Country/Region']=="Mainland China"]

Empty DataFrame
Columns: [Country/Region, Confirmed, Deaths, Recovered, Active]
Index: []

In [ ]:
countries[countries['Country/Region']=="US"]

Empty DataFrame
Columns: [Country/Region, Confirmed, Deaths, Recovered, Active]
Index: []

In [ ]:

countries[countries['Country/Region']=="India"]

Empty DataFrame
Columns: [Country/Region, Confirmed, Deaths, Recovered, Active]
Index: []

In [ ]:
countries['Country/Region']=="Mainland China"

0      False
1      False
2      False
3      False
4      False
       ...
108    False
109    False
110    False
111    False
112    False
Name: Country/Region, Length: 113, dtype: bool

In [ ]:
# Plot on World Map
import plotly.express as px
world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color="Confirmed",color_continuous_scale="reds",range_color=[0,10000000])
world_map

In [ ]:
world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color="Recovered",color_continuous_scale="greens",range_color=[0,10000000])
world_map

In [ ]:
# count of cases datewise
total_cases = data.groupby("ObservationDate")[["Confirmed","Deaths","Recovered","Active"]].sum().reset_index()
total_cases

    ObservationDate  Confirmed   Deaths  Recovered    Active
0        2020-01-22        557       17         30       510
1        2020-01-23       1097       34         60      1003
2        2020-01-24        941       26         39       876
3        2020-01-25       1437       42         42      1353
4        2020-01-26       2118       56         56      2006
..              ...        ...      ...        ...       ...
481      2021-05-17  163609626  3390170   99808931  60410525
482      2021-05-18  164231811  3404419  100552044  60275348
483      2021-05-19  164902903  3417763  101250071  60235069
484      2021-05-20  165182316  3430539  101886760  59865017
485      2021-05-21   32081489   655365   23479164   7946960

[486 rows x 5 columns]

In [ ]:
# Top countries having maximum confirmed and recovered cases
top = latest_data.groupby("Country/Region")[['Confirmed','Recovered']].sum().reset_index()
top = top.sort_values(['Confirmed'],ascending=False)
top.head()

    Country/Region  Confirmed  Recovered
54          France    5526555     324444
6        Argentina    3482512    3060145
71            Iran    2815882    2304824
70       Indonesia    1764644    1626142
38  Czech Republic    1656874    1603764

In [ ]:
top_20 = top.head(20)
top_20

     Country/Region  Confirmed  Recovered
54           France    5526555     324444
6         Argentina    3482512    3060145
71             Iran    2815882    2304824
70        Indonesia    1764644    1626142
38   Czech Republic    1656874    1603764
72             Iraq    1160494    1072026
74           Israel     839290     832279
68          Hungary     801025     661564
12       Bangladesh     786698     729039
77           Jordan     726432     710445
8           Austria     640293     620837
86          Lebanon     537887     507424
108         Morocco     516449     504757
96         Malaysia     498795     444540
111           Nepal     497052     374836
78       Kazakhstan     425397     385566
44          Ecuador     416621     354499
22         Bulgaria     416417     372968
59           Greece     387426      93764
14          Belarus     383302     373391

In [ ]:
# India
india = data[data['Country/Region']=="India"]
india

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
446,2020-01-30,NaN,India,1,0,0,1
509,2020-01-31,NaN,India,1,0,0,1
567,2020-02-01,NaN,India,1,0,0,1
629,2020-02-02,NaN,India,2,0,0,2
696,2020-02-03,NaN,India,3,0,0,3
...,...,...,...,...,...,...,...
299466,2021-05-20,Tripura,India,44359,455,37097,6807
299481,2021-05-20,Unknown,India,0,0,0,0
299492,2021-05-20,Uttar Pradesh,India,1651530,18588,1516508,116434
299493,2021-05-20,Uttarakhand,India,303940,5484,229813,68643
299521,2021-05-20,West Bengal,India,1209958,13895,1064553,131510

In [ ]:
# Find total number of states
india['Province/State'].nunique()

38

In [ ]:
# Find names of states
india['Province/State'].unique()

array([nan, 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadar Nagar Haveli', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Unknown', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Dadra and Nagar Haveli and Daman and Diu',
       'Lakshadweep'], dtype=object)

In [ ]:
india['Province/State'] = india['Province/State'].fillna("Unknown")

/tmp/ipykernel_5621/1748090106.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
india['Province/State'].unique()

array(['Unknown', 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadar Nagar Haveli', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Dadra and Nagar Haveli and Daman and Diu',
       'Lakshadweep'], dtype=object)

In [ ]:
india['Province/State'].nunique()

38

In [ ]:
#india_latest_data
india_latest_data = india[india['ObservationDate'] ==india['ObservationDate'].max()]
india_latest_data

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
298970,2021-05-20,Andaman and Nicobar Islands,India,6758,96,6401,261
298971,2021-05-20,Andhra Pradesh,India,1521142,9800,1302208,209134
298988,2021-05-20,Arunachal Pradesh,India,23159,89,20339,2731
298989,2021-05-20,Assam,India,353574,2507,297902,53165
299011,2021-05-20,Bihar,India,676045,4241,617397,54407
299045,2021-05-20,Chandigarh,India,57331,666,50592,6073
299052,2021-05-20,Chhattisgarh,India,936423,12295,842662,81466
299071,2021-05-20,Dadra and Nagar Haveli and Daman and Diu,India,9850,4,9174,672
299075,2021-05-20,Delhi,India,1409950,22579,1347157,40214
299111,2021-05-20,Goa,India,141567,2272,118487,20808
299127,2021-05-20,Gujarat,India,776220,9404,677798,89018
299133,2021-05-20,Haryana,India,722964,7205,653407,62352
299140,2021-05-20,Himachal Pradesh,India,172722,2595,136679,33448
299166,2021-05-20,Jammu and Kashmir,India,260057,3422,206081,50554
299169,2021-05-20,Jharkhand,India,324884,4714,293659,26511
299187,2021-05-20,Karnataka,India,2335524,23854,1776695,534975
299190,2021-05-20,Kerala,India,2263959,6852,1938887,318220
299215,2021-05-20,Ladakh,India,17025,172,15264,1589
299216,2021-05-20,Lakshadweep,India,5756,20,4072,1664
299236,2021-05-20,Madhya Pradesh,India,752735,7315,672695,72725
299242,2021-05-20,Maharashtra,India,5497448,85355,5026308,385785
299244,2021-05-20,Manipur,India,41909,646,34359,6904
299257,2021-05-20,Meghalaya,India,26927,389,20061,6477
299271,2021-05-20,Mizoram,India,9740,30,7407,2303
299283,2021-05-20,Nagaland,India,19284,245,14520,4519
299327,2021-05-20,Odisha,India,655899,2403,556501,96995
299361,2021-05-20,Puducherry,India,91465,1269,71919,18277
299365,2021-05-20,Punjab,India,523423,12716,443666,67041
299375,2021-05-20,Rajasthan,India,897193,7346,745873,143974
299424,2021-05-20,Sikkim,India,12204,217,8865,3122
299445,2021-05-20,Tamil Nadu,India,1734804,19131,1452283,263390
299449,2021-05-20,Telangana,India,544263,3060,495446,45757
299466,2021-05-20,Tripura,India,44359,455,37097,6807
299481,2021-05-20,Unknown,India,0,0,0,0
299492,2021-05-20,Uttar Pradesh,India,1651530,18588,1516508,116434
299493,2021-05-20,Uttarakhand,India,303940,5484,229813,68643
299521,2021-05-20,West Bengal,India,1209958,13895,1064553,131510

In [ ]:
top_state = india_latest_data.groupby("Province/State")[['Confirmed','Recovered']].sum().reset_index()
top_state = top_state.sort_values(['Confirmed'],ascending=False)
top_state.head(20)

    Province/State  Confirmed  Recovered
20     Maharashtra    5497448    5026308
15       Karnataka    2335524    1776695
16          Kerala    2263959    1938887
30      Tamil Nadu    1734804    1452283
34   Uttar Pradesh    1651530    1516508
1   Andhra Pradesh    1521142    1302208
8            Delhi    1409950    1347157
36     West Bengal    1209958    1064553
6     Chhattisgarh     936423     842662
28       Rajasthan     897193     745873
10         Gujarat     776220     677798
19  Madhya Pradesh     752735     672695
11         Haryana     722964     653407
4            Bihar     676045     617397
25          Odisha     655899     556501
31       Telangana     544263     495446
27          Punjab     523423     443666
3            Assam     353574     297902
14       Jharkhand     324884     293659
35     Uttarakhand     303940     229813

In [ ]:
top_state['Confirmed'].max()

5497448

In [ ]:
top_state[top_state['Confirmed']==top_state['Confirmed'].max()]['Province/State'].values[0]

'Maharashtra'